### ISSUE TITLE
Some Typos and other things

### ISSUE THREAD

**Issue by stonie81** [iamjoshk/home-assistant-collection#2]
Hi @iamjoshk,
the code in ESPHome/Sonicare/esphome_sonicare_ble.yaml helped me a lot, but it has some typos (sorry I don't know how to make a PR, so I opened an issue).
For example, at line 12 `lBigELittleE: INFO` should be `log: INFO`
and there are more of them at line 120 and 9 other lines dBigEice_class -> device_class
Another thing is that I used the esp-idf framework, and then I get errors with the variables/their format. So I had to change %d to %ld at line 150, and so on.
I also had problems in updating because of no pairing (so I think/interpreted the errors in the logs), so I found a [solution at the ha community](https://community.home-assistant.io/t/is-ble-client-pairing-bonding-possible/326013/24)
Just for information, I put my code below.
```
esphome:
  name: badezimmer-esp32

esp32:
  board: esp32dev
  framework:
    type: esp-idf
#     type: arduino

esp32_ble_tracker:
#  scan_parameters:
#    interval: 1000ms
#    window: 1000ms
#    active: true

# Enable logging
logger:
#  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret badezimmer_api_key

ota:
  - platform: esphome
    password: !secret badezimmer_ota_password

safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "badezimmer-esp32"
    password: !secret badezimmer_wifi_ap_password

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a 

ble_client:
#Andreas Zahnbürste
  - mac_address: 24:E5:AA:XX:XX:XX
    id: sonicare_Andrea
    name: Andreas Zahnbürste
    auto_connect: true
    on_connect: 
      then:
        - lambda: |-
            ESP_LOGE("custom", "Connected to Andreas Sonicare, trying to pair");
            id(sonicare_Andrea)->pair();

#Gunnars Zahnbürste
  - mac_address: 24:E5:AA:XX:XX:XX
    id: sonicare_Gunnar
    name: Gunnars Zahnbürste
    auto_connect: true
    on_connect: 
      then:
        - lambda: |-
            ESP_LOGE("custom", "Connected to Gunnars Sonicare, trying to pair");
            id(sonicare_Gunnar)->pair();

globals:

#Andreas Zahnbürste
  - id: sonicare_Andrea_connected
    type: bool
    restore_value: no 
    initial_value: 'false'

  - id: Andrea_battery_last_value
    type: int
    restore_value: yes

#Gunnars Zahnbürste
  - id: sonicare_Gunnar_connected
    type: bool
    restore_value: no 
    initial_value: 'false'

  - id: Gunnar_battery_last_value
    type: int
    restore_value: yes

binary_sensor:
#Andrea's Zahnbürste
  - platform: template 
    name: Andrea Zahnbürste
    id: sonicare_Andrea_ble_connection
    lambda: |- 
      return id(sonicare_Andrea_connected); 
    device_class: connectivity

#Gunnar's Zahnbürste
  - platform: template 
    name: Gunnar Zahnbürste
    id: sonicare_Gunnar_ble_connection
    lambda: |- 
      return id(sonicare_Gunnar_connected); 
    device_class: connectivity

switch:
  - platform: shutdown
    name: "BLEClient1 Shutdown"

  - platform: restart
    name: "BLEClient1 Restart"   

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Badezimmer Temperatur"
      id: badezimmer_temperatur
      oversampling: 16x
    pressure:
      name: "Badezimmer Luftdruck"
      id: badezimmer_luftdruck
    humidity:
      name: "Badezimmer Luftfeuchtigkeit"
      id: badezimmer_luftfeuchtigkeit
    address: 0x76
    iir_filter: 16x
    update_interval: 60s

  - platform: absolute_humidity
    name: "Badezimmer absolute Feuchtigkeit"
    temperature: badezimmer_temperatur
    humidity: badezimmer_luftfeuchtigkeit

# Gunnar
  - platform: ble_client
    ble_client_id: sonicare_Gunnar
    id: Gunnar_toothbrush_battery_value
    type: characteristic
    name: "Akkustand Gunnars Zahnbürste"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    notify: True
    unit_of_measurement: "%"
    device_class: "battery"
    state_class: "measurement"
    internal: True
    update_interval: 10s
    on_value:
      then:
        - lambda: |-
            if (x >= 0 && x <= 100) {
              id(Gunnar_battery_last_value) = x;
              ESP_LOGD("ble_sensor", "Battery value updated: %d", id(Gunnar_battery_last_value));
            } else {
              /* lambda ist immer C/C++ Code und deshalb sind Kommentare auch so Escaped */
              /* lambda is C/C++ code and therefore comments need to be escaped this way */
              ESP_LOGD("ble_sensor", "Received invalid battery value: %lf", x);
              /* ESP_LOGD("ble_sensor", "Received invalid battery value: %d", x); */
            }

# Gunnar
  - platform: template
    id: Gunnar_toothbrush_battery
    name: Gunnar Zahnbürste Battery
    lambda: |-
      return id(Gunnar_battery_last_value); 
    device_class: "battery"
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 0

# Andrea
  - platform: ble_client
    ble_client_id: sonicare_Andrea
    id: Andrea_toothbrush_battery_value
    type: characteristic
    name: "Akkustand Andreas Zahnbürste"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    notify: True
    unit_of_measurement: "%"
    device_class: "battery"
    state_class: "measurement"
    internal: True
    update_interval: 10s
    on_value:
      then:
        - lambda: |-
            if (x >= 0 && x <= 100) {
              id(Andrea_battery_last_value) = x;
              ESP_LOGD("ble_sensor", "Battery value updated: %d", id(Andrea_battery_last_value));
            } else {
              ESP_LOGD("ble_sensor", "Received invalid battery value: %lf", x);
            }

# Andrea
  - platform: template
    id: Andrea_toothbrush_battery
    name: Andrea Zahnbürste Battery
    lambda: |-
      return id(Andrea_battery_last_value); 
    device_class: "battery"
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 0
```
